fix: use tar.gz instead of zip because of error
*.zip causes this error below:

```
Error: An exception occurred within a child process:
  RuntimeError: Empty archive
```